package com.medieval.game.service;

/**
 * [TORRE_NARRATIVA] Catálogo dos 50 andares da Torre (S1). Cada andar tem uma ATMOSFERA (chegada),
 * um DESFECHO ({@code aftermath}, mostrado ao VENCER) e uma DERROTA ({@code defeat}, mostrada ao PERDER),
 * além do(s) MONSTRO(S) que o guardam (gauntlet sequencial); a cada 10 andares, um MVP de história. A
 * subida é a queda do Rei Arka contada de baixo pra cima. Texto exibido ao player = inglês (regra de UI;
 * PT vem do i18n tower.floor.<n>.{atmosphere|aftermath|defeat}). Ver docs/PLANO_TORRE_DESFECHO.md +
 * docs/LORE.md. Stats/balance ficam no TowerService (tunados pela sonda).
 */
public final class TowerFloors {

    private TowerFloors() {}

    /** Definição de um andar: atmosfera (chegada) + desfecho (vitória) + derrota + monstros (gauntlet) OU um MVP. */
    public record FloorDef(String atmosphere, String aftermath, String defeat, String[] monsters, String mvp) {
        public boolean isMvp() { return mvp != null; }
    }

    private static FloorDef floor(String atmosphere, String aftermath, String defeat, String... monsters) {
        return new FloorDef(atmosphere, aftermath, defeat, monsters, null);
    }
    private static FloorDef mvp(String mvp, String atmosphere, String aftermath, String defeat) {
        return new FloorDef(atmosphere, aftermath, defeat, new String[0], mvp);
    }

    // Índice = andar - 1 (1..50). 5 zonas de 9 + um MVP a cada 10.
    private static final FloorDef[] FLOORS = {
        // ── Zona 1 (1-9): Salões Baixos — a guarda caída ──────────────────────────
        floor("The first hall is cold for a place so high. The air doesn't fall from the windows — it rises, from a seam in the floor, smelling of tide and deep earth. There's a round mark on the stone the King ordered covered. It was his first command.",
              "The Gate Sentry topples, and from the seam in the floor the smell of tide rises stronger — as if something far below breathed easier. The round mark on the stone is wet now.",
              "The Gate Sentry beats you down onto the round mark, and the tide rising through the seam swallows you. The tower spits you out far below — soaked, and alive, for now.",
              "Gate Sentry"),
        floor("Spears lean in racks no hand has touched in years. One of them is still warm.",
              "The warm spear cools the instant the Sentinel falls. Whatever kept it warm climbed the stairs ahead of you — you simply didn't arrive in time to see it.",
              "The warm spear finds you first. You fall among the racks, and for years, perhaps, someone will still find it warm.",
              "Hall Sentinel"),
        floor("The torches burn with a pale, low flame that gives no heat, and your shadow falls the wrong way.",
              "With the Watchman undone, your shadow falls the right way again — for a moment. The pale flames all lean toward the stair above, like pointing fingers.",
              "The pale flame reaches you and gives no warmth. Your shadow falls the wrong way one last time, and goes out with you.",
              "Pale Watchman"),
        floor("A guardroom: dice still on the table, chairs pushed back, as if everyone rose at once and walked up.",
              "When the Husk collapses, the dice on the table finish rolling on their own. Every one comes up the same number.",
              "You drop beside the pushed-back chairs. The dice roll once more — and this time it is your number that doesn't come up.",
              "Deserter's Husk", "Deserter's Husk"),
        floor("Banners of Coroa de Arka rot on the walls, the stitched crown gone black.",
              "The stitched crown on the banner finally crumbles to black dust. What's left is only cloth — as if it had never belonged to any king.",
              "The Husk wraps you in a rotting banner of the Crown of Arka, and the hall takes you in as one more of its dead.",
              "Watchman's Husk", "Watchman's Husk"),
        floor("The stair narrows. Handprints climb the wall beside you — too many fingers on each.",
              "The handprints stop climbing the wall. The last one is still fresh, wide enough for yours to fit inside it.",
              "Too many hands drag you to the wall. You add your prints to the ones that climb — and the tower casts you back before they finish.",
              "Crawling Dead"),
        floor("A chapel to no god you know. The candles weep wax that pools and crawls toward the stairs up.",
              "He gutters out along with the candles. The wax that crawled up the stairs flows back, draining down into the seam below — feeding whatever lives there.",
              "The cold wax covers you slowly, like a vestment, and the chapel offers you up to some god you don't know.",
              "Wax-Eaten Priest"),
        floor("The dead here wear the garrison's colors and salute as you pass — then they reach for their blades.",
              "The last of them, as he falls, still raises a hand in one final salute — to you, or to something just behind you. You do not turn to check.",
              "They salute you as you fall — courteous to the end — and then the garrison claims you for its ranks.",
              "Loyal Unto Death", "Loyal Unto Death"),
        floor("The last hall before the upper gate stinks of old blood and new rust. Something big breathed here, recently.",
              "It falls with a crash that shakes the tower. Above, the upper gate groans open — unbarred from the inside, by no hand at all.",
              "The great thing that breathed here breathes over you. The upper gate shuts; you go down without ever passing through.",
              "Gate-Breaker"),
        mvp("The Fallen Captain", "He held this hall to the last, and was not allowed to die. His sword is still raised. His eyes follow you — and beg. He had a name, once — Sor Bramm Holt, Captain of the Gate.",
            "Sor Bramm Holt lowers at last the sword he held raised for years. For an instant, before the end, his eyes are only a tired man's eyes — and grateful. \"Higher,\" he breathes, \"the court lies. Don't listen.\"",
            "The sword he held raised for years comes down at last — on you. \"Forgive me,\" says Sor Bramm Holt, unable to stop. \"I choose nothing anymore.\""),

        // ── Zona 2 (11-19): A Corte — a nobreza podre ─────────────────────────────
        floor("Gold leaf peels from the walls in sheets. The floor is carpeted in coins no one stooped to gather.",
              "He dies clutching a fistful of coins that rust between his fingers before he even falls. Gold here cannot buy so much as one's own death.",
              "You fall among the coins no one gathered, and the Gilded Wretch closes his fingers around a fistful — as if you were just one more treasure left to rot.",
              "Gilded Wretch"),
        floor("Mirrors line the gallery. In each one, your reflection is a single heartbeat slow.",
              "In every mirror, your reflection topples a heartbeat after he does. And then — a heartbeat late — it smiles, though you are not smiling.",
              "Your reflection outlives you by a heartbeat, smiles, and stays. It is you who vanishes from the mirrors.",
              "Mirror-Bound"),
        floor("Portraits of nobles, every painted face scratched out — all but the eyes.",
              "He dissolves, and in the scratched portraits every remaining eye turns at once to follow you to the stair.",
              "The Faceless Courtier lays a hand where your face is. You go down without it, and in the scratched portraits there is one more pair of eyes.",
              "Faceless Courtier", "Faceless Courtier"),
        floor("A banquet long spoiled, the guests still seated, still chewing.",
              "The table falls silent at last. The guests slump over their plates, mid-bite — the feast, in the end, has finished eating them.",
              "They offer you a seat at the table. You sit, and begin, without meaning to, to chew.",
              "Feast-Rotted", "Feast-Rotted"),
        floor("Perfume thick enough to choke, laid over something sweeter and far worse beneath.",
              "With him, the perfume dies too. What lay beneath it rises unmasked — sweet, rotten, clinging to your throat all the way up the next stair.",
              "The perfume fills your lungs and what lies beneath fills the rest. You go down sweet and rotten, just as the court likes.",
              "Powdered Corpse"),
        floor("The throne-room's antechamber. Petitioners knelt here so long their knees fused to the stone.",
              "Freed from whatever held them kneeling, they pitch forward and go still. Not one of them faced the throne — every one stared at the floor.",
              "Your knees meet the stone and will not rise again. You join those who wait, faces to the floor.",
              "The Kneeling", "The Kneeling"),
        floor("A counting-house: ledgers stacked to the ceiling, every page the same name, written a thousand times.",
              "The ledgers fall open as he drops. The name written a thousand times is the King's — and beneath the last line, in fresh ink, is yours.",
              "The Tally-Keeper writes your name beneath the King's, a thousand times, quickly — before you've even finished falling.",
              "Tally-Keeper"),
        floor("Jewels grow from the walls like mold. They turn to follow you, the way eyes do.",
              "The jewels growing from the walls go dark all at once, blind again. The hall is only stone staring at stone.",
              "The jewels grow over you as you cool. The tower makes you one more pair of eyes in the wall.",
              "Jewel-Crusted Horror"),
        floor("The court's champion-at-arms, who never lost a duel and never fought a real one.",
              "He falls to a real blade for the first and last time. On his face, something almost like relief — to have finally lost a duel that was real.",
              "The Duelist of Lies finally 'wins' a real duel — yours. He will never know it was the only true one.",
              "Duelist of Lies"),
        mvp("The Coin-Eaten", "He counted his gold while the city burned. The rot found him full — and made him fuller. He offers you a price to turn back. He cannot understand that you won't take it. His name was Lord Casnar Vane, the crown's Treasurer.",
            "Lord Casnar Vane dies still naming a number, the price rising with each breath, as if somewhere there were still someone to pay it. When he falls silent, the stone beneath the court is warm, and the stairs ahead descend toward a red that runs upward.",
            "Lord Casnar Vane offers you a price, and this time you cannot refuse. The rot finds you with empty pockets, and fills them."),

        // ── Zona 3 (21-29): As Profundezas do Ritual ──────────────────────────────
        floor("Below the court the stone is warm. The stairs are wet, and the wet is red, and it flows up to meet you.",
              "His blood joins the red already climbing the steps and races on upward. All the blood in this tower is in a hurry to reach the top.",
              "Your blood joins the red climbing the steps, and for an instant you too are in a hurry to reach the top. Then the tower pulls you back down.",
              "Bleeding Acolyte"),
        floor("Censers swing on their own, breathing smoke that tastes of copper and old prayers.",
              "The censers stop, cold. The copper-and-prayer smoke is drawn downward, swallowed by the seam — like a breath drawn in by something far too large, down in the deep.",
              "The copper smoke fills your lungs like a prayer, and you exhale one last time into the seam.",
              "Censer-Wraith", "Censer-Wraith"),
        floor("A circle scored into the floor, scrubbed and re-cut a hundred times. The grooves run deep enough to drown in.",
              "He dissolves into the carved grooves and is gone — one more layer in a wound this floor has been reopening for years. The grooves look a little deeper now.",
              "You fall inside the circle, and the grooves take you in — one more layer in a wound that never closes.",
              "Circle-Warden"),
        floor("The faithful kneel facing down, repeating a word with no mouth-shape you can make.",
              "The chant breaks off mid-word. The silence it leaves has a shape — and the shape waits, patient, for someone to finish it. You climb quickly, before it can be you.",
              "Your mouth finds, on its own, the shape of the word. You go down chanting, and cannot stop.",
              "The Chanting", "The Chanting", "The Chanting"),
        floor("Crystals grow from the altars, red at the core. One of them pulses in time with your heart.",
              "The crystal that beat in your rhythm cracks and stops. For one breath, so does yours — and when it starts again, it beats a little slower, as if it had learned something.",
              "The crystal beats again — now to the rhythm of your stopping heart. It keeps your pulse after you are gone.",
              "Crystal-Hearted"),
        floor("Vials of royal blood line every shelf, each labeled with a date. The last one is today's.",
              "He topples, and the vial marked with today's date tips over. The blood does not run to the floor: it climbs the wall, eager, to join the rest already racing to the top.",
              "The Vintner labels a fresh vial with today's date, and fills it with you.",
              "Vintner of Blood"),
        floor("Something was born here and did not survive the birth. It is still trying.",
              "The thing that was still trying to be born stops trying. You cannot tell whether you killed it or simply let it rest at last. Both thoughts frighten you equally.",
              "Something pulls you into the thing still trying to be born. The two of you go down together, still trying.",
              "The Unborn Rite"),
        floor("The deeper altar. The blood doesn't pool — it climbs the walls, against the slope, toward the floors above.",
              "With it undone, the blood on the walls hesitates, pauses an instant — then climbs on anyway. It no longer needs servants: it has learned the way itself.",
              "Your blood climbs the wall against the slope, eager, without you. The Altar-Thing thanks you for the offering.",
              "Altar-Thing", "Altar-Thing"),
        floor("A throne-shaped chair of bone and gold: a rehearsal seat. Whoever sat here practiced being a king.",
              "He slumps in the bone throne, crownless at last, having rehearsed his whole life a coronation that was never his. High above, someone real is about to be crowned.",
              "The Pretender offers you the bone throne. You fall into it, seated, rehearsing, like all who came before you.",
              "The Pretender"),
        mvp("The Crowned Echo", "It wears the King's shape, his walk, his voice — a hollow rehearsal for the thing at the top. It greets you by name, in the King's voice, and asks why you've come so far to kill a man you were sent to save. It owns no name of its own — only his.",
            "The Echo unravels, and for a moment it wears the King's grief instead of his face. \"You'll see him soon,\" it says, in the King's voice. \"Tell him I tried to be him.\" Then the voice fades, and only an echo of an echo is left, climbing the stair.",
            "The Echo wears your face now, alongside all the others. \"You'll see him soon as well,\" it says, in the King's voice — and a little of yours."),

        // ── Zona 4 (31-39): A Sombra do Rei ───────────────────────────────────────
        floor("The light here comes from below now, the wrong shade of pale, and it casts no shadows at all.",
              "It leaves no body, casts no shadow even in death. You climb on — and only a few steps later notice that you have stopped casting one too.",
              "The light from below snuffs out your shadow first, and then the rest. You go down casting nothing.",
              "Shadeless One"),
        floor("The walls breathe in. Warm air pulls past you, downward, always downward.",
              "The walls exhale for the first time and release it. The warm wind reverses and begins to push you upward, eager, like one delivering a parcel long awaited.",
              "The walls breathe in, and you go with them — down, always down, the way the air always wanted.",
              "Breath-Taken"),
        floor("Things dredged up from somewhere deeper, wearing stone and gold like skin that doesn't fit.",
              "It sheds the stone and gold it wore like skin and slides back toward the seam — called home by whatever dredged it up from the deep. You do not follow.",
              "Something dredges you down with it into the seam. Below, they will decide what skin you are to wear.",
              "Dredged Horror", "Dredged Horror"),
        floor("The King's study. His notes cover every surface, in a hand that grows less human page by page.",
              "He dies face-down in the King's notes. The last legible line, in a barely-human hand, reads: it was never a tower. it is a throat. And you are climbing up the inside of it.",
              "You sink into the King's notes, and the hand that finishes your fall is no longer human.",
              "Ink-Drowned Scholar"),
        floor("A menagerie of the changed — courtiers, guards, priests — all melting toward one shape you cannot name.",
              "The half-melted things come apart, and for an instant you glimpse the single shape they were all becoming. It has the King's face.",
              "You begin to melt toward that single shape, and for an instant, before the end, you wear the King's face.",
              "The Becoming", "The Becoming"),
        floor("A whisper in a voice almost like the King's promises you the thing you want most, and calls you by your own name.",
              "It dies mid-promise, having offered you everything you most want. The silence afterward is the first thing in this tower that hasn't lied. You almost miss the voice.",
              "The whisper promises you everything, and you believe it. You go down smiling, the thing you wanted most in your empty hands.",
              "Honeyed Whisper"),
        floor("The air hums, low and steady — a heartbeat far too large to belong to anything that ought to live.",
              "The flesh stops, but the hum does not. It goes on without it, down in the deep, low and steady — a heartbeat that never needed a body.",
              "The too-large heartbeat swallows you into its rhythm. You become one more sound it makes, down in the deep.",
              "Hum-Made-Flesh"),
        floor("The last of the King's true guard, who followed him down and could not follow him through.",
              "The last of them falls before the threshold he could not cross, his outstretched hand pointing the way up, where he was forbidden to follow the King. \"Bring him back,\" he asks, \"or bring nothing.\"",
              "You fall before the threshold, as he fell. His hand points the way up — which neither of you will take.",
              "Threshold Guard", "Threshold Guard"),
        floor("A door scorched from the inside. Something tried to keep itself in. It failed.",
              "The seal breaks for good. Whatever it tried to keep locked away is long gone — up, ahead of you, toward the King. The scorched door swings open onto a stair that smells of tide.",
              "The scorched door shuts with you on the inside. What it could not keep in now keeps you.",
              "The Failed Seal"),
        mvp("The Xamã", "The man the sea spat back, years ago, declared dead and returned wrong. He lifts no hand against you. He only laughs, and bids you climb. \"Give the poor king his peace,\" he says. \"It's all I ever wanted.\" They called him Oren, the Drowned — the man who lit the rite.",
            "Oren does not fall: he lets go, smiling, sliding back toward the sea that spat him out. \"Peace,\" he repeats, delighted, as he comes apart. \"You'll give it to him for me.\" Above the body that does not stay, the tower stops being a tower — the stairs go on, the walls give up.",
            "Oren laughs as you fall. \"Almost,\" he says, gently. \"Next time, give him your peace — and mine.\" The sea carries you down."),

        // ── Zona 5 (41-49): O Limiar ──────────────────────────────────────────────
        floor("Past the Shaman, the tower stops being a tower. The stairs go on; the walls forget to.",
              "He steps off an edge that isn't there and is gone. The stairs go on; you go on with them, because there is nothing left but to climb. Behind you has stopped existing too.",
              "You take one step too many, and the tower that is no longer a tower lets you fall out of everything. Then it gives you back, because it isn't done with you.",
              "Edge-Walker"),
        floor("You can no longer tell up from down. The hum is in your teeth now.",
              "When it dies you fall — up, down, impossible to say — and land climbing, as if the stair caught you and carried on. The hum in your teeth has a rhythm now. It is a heartbeat.",
              "You fall up and down at once, and the hum that has a rhythm rocks you all the way to the bottom.",
              "Vertigo-Thing", "Vertigo-Thing"),
        floor("Shapes that are almost people, almost beasts, almost nothing — still deciding what to be.",
              "It dies before it could decide what to be — man, beast, or nothing. You spare it the choice without meaning to; perhaps it is the only mercy this tower allows. High above, someone has already chosen for everyone.",
              "You stop deciding what you'll be, mid-strike. The tower decides for you, and sends you back to begin again.",
              "The Undecided"),
        floor("The floor is skin-warm and yields like a held breath. Far below, something vast turns over in its sleep.",
              "The dream bursts like a held breath let go. Far below, the vast thing stops turning and goes still — not the stillness of falling back asleep, but of something that, after a long time, has decided to wake.",
              "You sink into the warm floor as into a held breath. Far below, the vast thing feels you arrive, and nearly wakes.",
              "Sleeper's Dream", "Sleeper's Dream"),
        floor("Royal blood, fresh, runs UP the stairs past you, eager, toward the top.",
              "The tide breaks around the falling thing and rushes on, up the stairs, leaving you behind. The blood has somewhere it needs to be, and it is almost there. You quicken your step, so as not to arrive after it.",
              "The eager tide carries you up the stairs for an instant — and then drops you, in no hurry for you, and runs on down again.",
              "The Eager Tide"),
        floor("A throne of the King's old banners, burned and rebuilt, burned and rebuilt.",
              "It burns one last time and, this time, is not rebuilt. The throne of banners collapses into embers that, of course, rise instead of falling. Even fire knows the way.",
              "You burn along with the throne of banners, and like everything here, your ashes rise instead of falling.",
              "Ash-Crowned"),
        floor("The whispers stop. The silence is worse — it is listening back.",
              "You strike the dark and it listens to that too — and keeps it. The silence that follows is fuller than before, by exactly one death. Something high above heard you arrive.",
              "The dark listens to your fall and keeps it. You become one more silence in its collection.",
              "The Listening Dark"),
        floor("A reflection of you climbs beside you, one step behind, smiling.",
              "You cut down the thing wearing your face, and it falls one step behind you, still smiling — as if it doesn't mind, as if it will simply try again higher up. You do not look back for the rest of the climb.",
              "The thing with your face finally catches you. It climbs; you descend. It is still smiling.",
              "The One Step Behind"),
        floor("The last door. Light leaks under it, the color of a wound. Beyond it, you hear a man weeping.",
              "The door swings open. The weeping does not stop: it is louder now, just beyond it, and it knows your footsteps. \"You took your time,\" says the King's voice. \"Good. Good.\"",
              "The weeping stops when you fall, just for an instant. \"Ah,\" says the King's voice, disappointed. \"So close. Come back. I'll wait.\"",
              "The Weeping Threshold"),
        mvp("Rei Arka", "King Arka, wreathed in a light that is not his own — and beneath it, for a flicker, the man who founded a kingdom. He fights to ascend; he does not understand he is only a key. When he falls, he will beg. Arka, the Founder — the man beneath the key.",
            "The borrowed light abandons him, and Arka is only a man again — on his knees, the key spent, the whole kingdom he founded contained in a trembling body. Far below, what the light held waiting goes quiet, attentive. Everything in this tower has waited for this moment. Now he looks at you, and opens his mouth to beg.",
            "The borrowed light strikes you down — and Arka, beneath it, looks almost relieved. \"Stronger,\" he begs, as you descend. \"Come back stronger. End this.\""),
    };

    /** Definição do andar (1..50). Acima de 50 reaproveita o 50 (não deveria acontecer na S1). */
    public static FloorDef forFloor(int floor) {
        int idx = Math.max(1, Math.min(floor, FLOORS.length)) - 1;
        return FLOORS[idx];
    }

    public static int maxFloor() { return FLOORS.length; }
}
