package com.medieval.game.quest;

import com.medieval.game.enums.Attribute;
import com.medieval.game.enums.KingdomQuestType;
import com.medieval.game.quest.QuestDialog.QuestOption;
import com.medieval.game.quest.QuestOutcome.*;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Conteúdo das quests interativas (decisão única): história + opções por {@link KingdomQuestType}.
 * Texto voltado ao jogador em INGLÊS (i18n pro PT depois). Recompensas = multiplicadores da reward
 * base da quest. Quest sem entrada aqui = não-interativa (encontro aleatório). Ver docs/PLANO_QUESTS_INTERATIVAS.md.
 */
public final class InteractiveQuests {

    private InteractiveQuests() {}

    // DCs do roll d20 (1d20 + floor(attr/4) vs DC; nat 1 falha / nat 20 passa)
    private static final int EASY = 10, MEDIUM = 14, HARD = 18, EPIC = 22;

    private static final Map<KingdomQuestType, QuestDialog> DIALOGS = new EnumMap<>(KingdomQuestType.class);

    public static Optional<QuestDialog> dialogFor(KingdomQuestType qt) {
        return Optional.ofNullable(DIALOGS.get(qt));
    }

    public static boolean isInteractive(KingdomQuestType qt) {
        return DIALOGS.containsKey(qt);
    }

    // ── Helpers de autoria ──────────────────────────────────────────────────────
    private static QuestOutcome peace(double b, double x, int drop, String n) { return new Peaceful(b, x, drop, n); }
    private static QuestOutcome fight(double b, double x, int drop, String win, String lose) { return new Fight(b, x, drop, win, lose); }
    private static QuestOutcome check(Attribute a, int dc, QuestOutcome ok, QuestOutcome fail) { return new Check(a, dc, ok, fail); }
    private static QuestOption opt(String id, String label, String hint, QuestOutcome o) { return new QuestOption(id, label, hint, o); }
    private static void put(KingdomQuestType qt, String intro, QuestOption... opts) { DIALOGS.put(qt, new QuestDialog(intro, List.of(opts))); }

    static {
        // ── Quest RARA da Luna (cachorra). O collect é special-cased no KingdomService (chance de pet,
        //    sem loot); os outcomes abaixo são placeholders e NÃO são resolvidos. [PETS] ──
        put(KingdomQuestType.RESCUE_STRAY_DOG,
            "A trembling stray dog lies in the mud, sick and whimpering. She looks up at you with tired, hopeful eyes.",
            opt("help",  "Help the dog", "no reward — but maybe a loyal friend", peace(0, 0, 0, "You tend to her.")),
            opt("leave", "Walk away",    "",                                      peace(0, 0, 0, "You leave her be.")));

        // ── Fishing — Bone Gorge ────────────────────────────────────────────────
        put(KingdomQuestType.PATROL_COAST,
            "Smugglers are unloading crates on the misty shore.",
            opt("hail",  "Hail them openly",       "", peace(0.8, 0.8, 8,  "They slip you a bribe and you turn your back without a question. Only on the walk home do you notice every crate bore the same salt-stained seal — the one the tide leaves on what it has already claimed.")),
            opt("ambush","Ambush the smugglers",   "", fight(1.8, 1.6, 30, "You break their ring and seize the haul before they can run. Only after, prying the lids, do you find the salt-crusted seal stamped on every crate — the mark the tide leaves on cargo it has already promised to itself.", "They were ready for you, and the blades come faster than the bribes. You limp into the fog empty-handed, and the surf at your back keeps a low, patient rhythm, as if it had wagered on this all along.")),
            opt("tally", "Slip in and tally cargo", "DEX " + EASY, check(Attribute.DEXTERITY, EASY,
                         peace(1.5, 1.4, 20, "You count every crate unseen and sell the tally to those who pay for it. Your buyers never explain why the cargo manifests all end at the same stretch of black water — and you have learned not to ask."),
                         fight(1.4, 1.3, 20, "A plank creaks underfoot, and they turn with steel already drawn — but you cut your way clear of the circle. The fight leaves you breathless on the strand, and the waterline has crept up to your boots while your back was turned, closer than any tide should climb.", "Caught flat-footed among the crates, you fend off their blows just long enough to break for the dark. You wash up further down the shore than your feet could have carried you, the cold sea unwilling to say how you got there."))));

        put(KingdomQuestType.EXPLORE_REEFS,
            "Strange lights pulse beneath the reef.",
            opt("mark", "Mark the spot and leave", "", peace(0.8, 0.8, 8,  "You chart the lights and report back without wetting a boot. That night the same glow blooms in your dreams, patient and rising, as if the deep had memorized your face in return.")),
            opt("dive", "Dive into the dark water", "", fight(1.8, 1.6, 30, "A lurking eel coils out of the murk and strikes — and you open it from gill to tail. As it drifts down it joins the pale shapes already waiting on the bottom, and you realize the light was never the eel at all, but something further below that uses it for a lure.", "A lurking eel takes you by surprise, and the cold dark folds over your head before you can fight free. You break the surface gasping a long way from where you went under, the deep letting you go this once — not freeing you, only deciding it is not yet time.")),
            opt("read", "Read the currents",        "DEX " + EASY, check(Attribute.DEXTERITY, EASY,
                        peace(1.5, 1.4, 20, "You trace the safe channels and lift the sunken treasure free. The drowned hands that held it let go too easily — as if the sea were lending, not surrendering, and means to be repaid."),
                        fight(1.4, 1.3, 20, "A riptide hauls you sideways into the eel's lair, and you carve your way out through teeth and current both. You crawl onto the reef wrung out and shaking, certain now that the channel did not betray you by accident — the water steered you there.", "A riptide drags you down into the dark before you can read its turn, and the reef closes around you like a fist. You come to half-buried in the shallows with empty hands and a memory full of cold, the sea having taken its toll and left you to count it."))));

        put(KingdomQuestType.SALVAGE_THE_WRECK,
            "A half-sunk galleon groans on the rocks, its hold still full.",
            opt("float", "Take what floats free", "", peace(0.8, 0.8, 8,  "You gather the drifting cargo without so much as a splash. The crates that stayed below did not sink — they were pulled, and whatever pulled them watched you take the rest.")),
            opt("pry",   "Pry open the hold",     "", fight(1.8, 1.6, 35, "Trapped scavengers lunge from the flooded dark, and you cut them down one by one until the hold is yours. They had not been picking the wreck clean so much as guarding it, and they died facing inward, toward the deepest water in the hull.", "The scavengers swarm thicker than you reckoned, and the sea pours through the breach to back them. You stagger out as the hold drinks itself full behind you, the cold rising at your heels with the unhurried certainty of something that knows you cannot outrun it forever.")),
            opt("brace", "Brace the hull, search", "STR " + MEDIUM, check(Attribute.STRENGTH, MEDIUM,
                         peace(1.6, 1.4, 25, "You brace the buckling hull on your shoulders and strip the hold clean. The timbers shudder against you the whole time, slow and deliberate, like something below testing how much weight you can hold before the sea decides to keep you too."),
                         fight(1.4, 1.3, 20, "The hull gives under your shoulder, and the scavengers spill out with it — you put them down in the rushing dark and haul yourself clear. The galleon settles deeper as you go, groaning like it grudges you the escape it almost denied.", "The wreck shifts as you strain against it and pins you to the boards while the water climbs your chest. You wrench free at the last and surface with nothing but your life, and the half-sunk hulk seems to watch you flee, in no hurry, sure of the next time."))));

        put(KingdomQuestType.CLEAR_PIRATE_COVE,
            "The cove reeks of rum and gunpowder — pirates, and plenty of them.",
            opt("toll",  "Negotiate a toll",       "", peace(0.8, 0.8, 8,  "Coin changes hands and the pirates wave you through, grinning. They are not afraid of you, and on the way out you understand why: men who live on this coast learn there are far worse landlords than other men, and they all live underwater.")),
            opt("storm", "Storm the cove",          "", fight(1.9, 1.7, 35, "You scatter the crew across the sand and claim the reeking cove for your own. The survivors do not flee inland but wade out into the breakers to be gone, choosing the dark water over your steel, as if it were the kinder master after all.", "Outnumbered three to one, you give ground until the surf is at your back and then break for it through the spray. The pirates do not press the chase to the waterline — they have learned not to, and the reason for it laps cold around your knees as you wade away.")),
            opt("lines", "Cut their mooring lines", "DEX " + MEDIUM, check(Attribute.DEXTERITY, MEDIUM,
                         fight(2.2, 1.9, 40, "With their ships dragged out on the tide, the pirates panic, and you fall on them while they cry after the drifting hulls. The cove is yours by dusk, but the freed ships do not founder on the rocks as they should — they slide out and under, drawn down whole and quiet.", "They rally faster than the chaos should allow, closing ranks before you can press the advantage, and the weight of them bears you back. You break off bloodied into the shallows, the cove still theirs, the sea still listening."),
                         fight(1.5, 1.4, 25, "A lookout marks you mid-cut and the cove erupts, but you trade the ropes for your blade and carve room to breathe. You win clear with the haul half-taken, and the loosed lines trail off into black water that swallows them without a splash.", "Caught with a knife at the ropes and no hand free for your sword, you are beaten back across the sand before you can recover. You stumble into the surf to lose them, and the cold closes round you almost fondly, like it had been saving your place."))));

        put(KingdomQuestType.DEEP_SEA_RAID,
            "A reaver fleet anchors off the gorge, raiding at dawn.",
            opt("hold",   "Raise the alarm and hold", "", fight(1.8, 1.6, 35, "You sound the alarm and hold the shingle until the reavers break on your line and pull back to their ships. Watching them row out, you notice none of the dead they leave behind stay on the sand — the receding tide gathers them up and carries them off, tidy as a host clearing plates.", "The line buckles where the reavers press hardest, and you fall back over your own wounded as the shore is lost. You drag yourself out of the fight wounded and spent, the gorge fog rolling in to hide both the enemy and the cold thing the sea makes of the fallen.")),
            opt("sink",   "Sink the flagship by night", "DEX " + HARD, check(Attribute.DEXTERITY, HARD,
                          peace(2.2, 1.9, 30, "You open the flagship's belly to the sea and the panicked fleet scatters before dawn. The drowning reavers do not thrash for long — the water takes them down smoothly, almost gently, the way it takes everything it has been waiting for."),
                          fight(1.5, 1.4, 25, "An alarm bell splits the night and the deck floods with reavers, but you cut a path to the rail and throw yourself into the black water. You strike out for shore through a sea that seems to push and pull at once, and reach the rocks half-drowned but breathing.", "The alarm bell rings before your work is done, and the reavers drive you off the deck and into the cold. You are hauled from the water further down the coast, lungs full of brine and barely alive, with no memory of the hands that let you go."))));

        put(KingdomQuestType.HUNT_SEA_MONSTER,
            "The leviathan surfaces, jaws wide enough to swallow a longboat.",
            opt("face", "Face it head-on",        "", fight(1.6, 1.5, 40, "You ride the swell up under its jaw and drive your blade clean through its eye, and the great bulk shudders and sinks. The carcass does not float as dead things should — it slides straight down into the dark, drawn under to wherever such things are kept.", "The jaws snap shut a hand's breadth from you and the shockwave hurls you against the rocks, breaking you against the stone. You come to broken and bleeding on the strand, the leviathan gone back below, the tide already nosing at your heels to see if you will keep.")),
            opt("lure", "Lure it onto the shoals", "LUCK " + HARD, check(Attribute.LUCK, HARD,
                        fight(2.2, 2.0, 45, "It chases your boat onto the shoals and grounds itself thrashing in the shallows, where you finish it at your leisure. Even beached and dying it strains toward the deep, head turned to the open water, as though something out there were calling it home.", "It heaves itself off the bar before you can strike and turns on you in a froth of fury, scattering your plan in the spray. You bail and row for your life, and the gorge swallows your gambit whole — boat, haul, and nerve — sparing only you, and that grudgingly."),
                        fight(1.4, 1.3, 35, "It refuses the bait and meets you in deep water instead, but you hook a blade in its hide and ride out its rage until it tires and dives. You drift home wrung-out and victorious, uneasily aware the deep let you keep this kill.", "It will not be led, and meets you where the water has no floor — your gambit drowns the moment it begins. You are dragged under and spat back up by a riptide you cannot explain, washing ashore with nothing, certain the sea simply was not finished with you."))));

        // ── Mining — Black Iron Mines ───────────────────────────────────────────
        put(KingdomQuestType.ESCORT_MINERS,
            "Miners refuse to enter — they swear something moved in the dark.",
            opt("walk",  "Walk them in, torches high", "", peace(0.8, 0.8, 8,  "Torches high, you march the miners in and the dark stays empty enough to work. But the rock wall under your palm is warm, faintly, like a flank rising and falling — and the miners pick at it anyway, because the ore pays and they have stopped letting themselves notice.")),
            opt("hunt",  "Hunt whatever's down there", "", fight(1.8, 1.6, 30, "You track it down a dripping side-shaft and corner it against the rock, and end it with three hard blows. Where it falls the stone is warm and faintly wet, and the dark patch it leaves spreads slow, as if the wall itself were weeping over the kill.", "It drops on you out of a side-shaft you never marked and drives you back up the slope, blow by blow, until you reach the light. You stumble out empty-handed, and behind you the deep tunnels seem to settle and sigh, the way a body does when a fever passes.")),
            opt("listen","Listen to the rock",         "LUCK " + EASY, check(Attribute.LUCK, EASY,
                         peace(1.5, 1.4, 20, "You press your ear to the stone, hear the slow thing shift, and lead the miners wide around it. What you heard was not footsteps and not breathing, but something between the two — a pulse in the deep rock, keeping time, in no hurry at all."),
                         fight(1.4, 1.3, 20, "You read the rock wrong, and the thing you thought was below drops on you from above — but you keep your feet and fight it back into the dark. You herd the shaken miners out into daylight, hands still ringing from a stone that felt warmer than any rock should.", "You misjudge the slow pulse in the wall, and the dark has the better of you before you understand your mistake. The miners haul you up by the heels into the light, and you swear the breathing in the rock went quiet only once you had stopped fighting it."))));

        put(KingdomQuestType.CLEAR_CAVES,
            "Cave-ins sealed a tunnel — and something is digging back out.",
            opt("shore", "Shore it up and retreat", "", peace(0.8, 0.8, 8,  "You wall up the breach and pull every miner back to safer ground. Behind the fresh stone the digging does not stop — it only slows, and the new mortar comes away wet and red on your hands, though no one was hurt.")),
            opt("dig",   "Dig through and meet it", "", fight(1.8, 1.6, 30, "You break through the fresh-packed stone and meet the digger nose to nose, putting it down before it can burrow away. Its blood is the same slow dark seep that wells from the cut rock around you, and you cannot say, after, which of you the wall was bleeding for.", "It claws through the barrier before you do and bursts out among you, routing the miners and driving you back up the tunnel. You retreat into the light empty-handed, the breach behind you already healing over with a wet, knitting sound that no honest rockfall ever made.")),
            opt("seam",  "Find the weak seam",      "STR " + EASY, check(Attribute.STRENGTH, EASY,
                         peace(1.6, 1.4, 20, "You find the weak seam, strike it once, and drop the whole tunnel onto the thing as it digs. The rockfall muffles a sound that was almost a moan — and where the seam split, the fresh stone seeps a slow dark warmth, as if the mine itself were bleeding from the wound."),
                         fight(1.4, 1.3, 20, "The seam will not split clean, and the digger reaches you before the roof comes down — so you meet it blade to claw and force it back into its hole. You limp out with the way half-sealed, your hands stained dark from a rock that bled where you struck it.", "The seam holds fast under your blows and the digger is on you, burying you in loose debris as it closes the last of the gap. You claw free and flee with nothing, and the warm, breathing dark lets you go, as patient with your failure as it is with the ore."))));

        put(KingdomQuestType.SHORE_UP_TUNNELS,
            "Support beams are splintering; the whole level could drop.",
            opt("brace", "Brace what you can",       "", peace(0.9, 0.9, 8,  "You wedge the splintering beams back into place and buy the level another season of digging. The timbers hold, but they flex against your hands with a slow give that wood should not have — as though the walls were breathing in, holding it, waiting for you to leave.")),
            opt("clear", "Clear the nesting beasts", "", fight(1.8, 1.6, 30, "You go crack by crack with torch and steel and burn out every crawling thing that had taken root in the splintered beams. The cleared fissures weep a thin warm damp once the nests are gone, like a wound cleaned out, and you try not to wonder what they were feeding on.", "The nest is deeper than the cracks let on, and the swarm pours out faster than you can cut it, driving you back to the shaft mouth. You retreat into the light with nothing won, the level still groaning behind you in a slow, living rhythm you would rather not name.")),
            opt("heave", "Heave a pillar into place","STR " + MEDIUM, check(Attribute.STRENGTH, MEDIUM,
                         peace(1.6, 1.4, 25, "You heave the fallen pillar upright and the whole gallery settles back into silence. Your hands come away slick where you gripped the stone, and the warmth of it stays in your palms long after, like the touch of something that was glad to be steadied."),
                         fight(1.4, 1.3, 20, "The pillar slips from your grip and the crash stirs the things nesting below — but you hold your ground and beat them back into the dark before they can swarm. You shoulder the beam home at last, hands slick and warm where they gripped the living rock.", "The pillar twists as it falls and pins your leg to the floor while the roused nest boils up around you. You drag yourself free by inches and crawl for the light empty-handed, the warm stone clinging to your blood as if reluctant to let the wound close."))));

        put(KingdomQuestType.RETRIEVE_LOST_ORE,
            "A cart of black iron vanished down a side shaft.",
            opt("track", "Track the cart's trail", "DEX " + EASY, check(Attribute.DEXTERITY, EASY,
                         peace(1.5, 1.4, 20, "You follow the cart's ruts to a hidden stash and haul the black iron back into the light. The ore is warm through the sacking and grows heavier the longer you carry it, as if something deep below had not finished claiming it and resents the loss."),
                         fight(1.4, 1.3, 20, "The ruts lead you straight into a gremlin warren, and you have to fight your way back out with the cart in tow. You win clear hauling the black iron, every nugget warm through the sack and heavier than it has any right to be, as if it would rather have stayed down there.", "You lose the trail at a fork, then lose your footing on the wet stone, and the dark swallows both you and the cart. You crawl back toward the light with nothing, the lost ore left to the deep — which, you suspect, is exactly where it wished to go."))),
            opt("fight", "Fight the gremlin hoarders", "", fight(1.8, 1.6, 30, "You rout the chittering gremlins from their heap and reclaim every bar of black iron they had dragged down. They fought hardest not for their own lives but to keep the ore in the dark, and the recovered metal pulses faintly warm against your arms all the way up.", "The little wretches come in numbers the dark keeps hiding, and they swarm you off your feet and back up the shaft. You retreat bleeding and ore-less, the warren behind you settling into a low contented hum, the mine glad to keep what it has dragged below.")));

        put(KingdomQuestType.PURGE_INFESTATION,
            "The lower mines crawl with chittering things.",
            opt("smoke",    "Smoke them out",        "", peace(0.9, 0.9, 8,  "You choke the shafts with smoke and the chittering swarm pours up and out of the mine. They do not scatter blindly — they all flow the same way, downhill and inward, toward the deep heart of the rock, as if going home to whatever sent them.")),
            opt("wade",     "Wade in, blade first",  "", fight(1.9, 1.7, 35, "You wade hip-deep into the chittering tide and carve a path clean through to the heart of the swarm. The vermin you cut down do not crawl away to die but drag themselves downward, toward the deep rock, going home to bleed where the stone runs warm.", "The tide of vermin closes over you faster than you can cut, dragging at your arms and legs until the floor is lost beneath them. You tear yourself loose and flee up the shaft, the swarm flowing back down behind you in a single eager current, as if called.")),
            opt("collapse", "Collapse the nest tunnel","STR " + HARD, check(Attribute.STRENGTH, HARD,
                            peace(2.0, 1.8, 30, "One mighty blow brings the ceiling down and buries the whole nest in a heartbeat. The collapsed stone settles with a long, low groan that rolls up from far below the nest you killed — something vast down there has felt the wound, and remembered the shape of your hand."),
                            fight(1.5, 1.4, 25, "Your charge against the keystone fails to bring the roof down, and the disturbed nest pours out at you — but you hold the chokepoint and butcher them as they come. You stagger out the victor, ears full of a low groan rolling up from below that no falling rock would make.", "The keystone holds, the nest empties itself onto you, and the half-loosed ceiling comes down across your retreat all at once. You drag yourself clear of the rubble by your fingertips and flee, the deep mine sighing shut behind you, content to keep its brood and its grudge."))));

        put(KingdomQuestType.DEFEAT_CAVE_BEAST,
            "A hulking thing of stone and tusk blocks the deepest vein.",
            opt("strike", "Strike it down",        "", fight(1.6, 1.5, 40, "You wear the beast down blow by grinding blow until the great mass of stone and tusk comes crashing to the cavern floor. It falls across the deepest vein it had guarded, and the rock beneath it darkens slowly, as though something below were drinking what spills from the kill.", "Its tusk catches you across the ribs and slams you into the wall, and the dark goes quiet and close around you. You wake later slumped at the vein's edge with empty hands, the beast gone back into the deep, the warm stone at your cheek breathing slow against your skin.")),
            opt("plates", "Spot the cracked plates","DEX " + HARD, check(Attribute.DEXTERITY, HARD,
                          fight(2.2, 2.0, 45, "You read the seams in its stone hide, strike the cracked plate dead center, and the whole beast shatters apart like quarried rock. The deepest vein lies open behind it now, the fresh-broken face beaded with a warm dark dew that no honest ore should weep.", "The cracked plate was a feint — it turns into your blow and gores you, hurling you down the slope away from the vein. You crawl out of reach and out of the deep, leaving the beast its post, the dark closing patiently over the way you came."),
                          fight(1.4, 1.3, 35, "You misjudge the grain of its hide and have to trade blows the hard, brutal way — but you outlast it, and it sinks at last across the open vein. Your arms ache to the bone, and the warm rock underfoot seems to throb in time with your own hammering pulse.", "You read its hide wrong, and the beast tramples your plan and very nearly you, driving you broken from the vein. You haul yourself up the shaft on a useless leg, the deep dark letting you go without a sound, in no hurry, certain you will be back."))));

        // ── Combat — Cursed Fortress ────────────────────────────────────────────
        put(KingdomQuestType.DEFEND_WALLS,
            "Raiders mass at the gate as the horn sounds.",
            opt("hold",   "Hold the wall",     "", fight(1.8, 1.6, 30, "You meet the raiders at the parapet and throw them back over the edge until the assault breaks against the stone. Yet as they fall they do not curse the wall — they fix their eyes past you on the King's Tower, faces lit with the same sick hope, like men finally let in to the thing they came to serve.", "The raiders force a breach faster than you can plug it and the press of them sweeps you back off the wall. You are carried away in the rout, bruised and reeling, and the last thing you see is the enemy pouring not toward the keep but toward the tower's sickly glow, drawn like iron to a lodestone.")),
            opt("parley", "Parley for time",   "LUCK " + EASY, check(Attribute.LUCK, EASY,
                          peace(1.4, 1.4, 15, "Your words stretch the standoff long enough for reinforcements to arrive, and the raiders melt back into the hills. Yet they never once looked at the gate they came to break — their eyes kept lifting past the walls to the King's Tower, the way the faithful turn toward something they have already decided to serve."),
                          fight(1.4, 1.3, 20, "They answer your parley with a sudden charge, but you are not caught flat — you draw and hold the breach until they break and stream away. They flee not into the open hills but inward and upward, toward the tower's light, and you let them go, sick at the sight.", "The talk fails mid-sentence and the gate gives way, the falling timbers and the surge behind them burying your stand. You are dragged from the wreckage by your own retreating men, and through the smoke you watch the raiders kneel, every helm bowed toward the high spire."))));

        put(KingdomQuestType.CLEAR_DUNGEON,
            "The dungeon below the keep still holds the old garrison's ghosts.",
            opt("sweep", "Sweep it cell by cell", "", fight(1.8, 1.6, 30, "You go down the row cell by cell, laying the restless garrison to rest one grasping shade at a time. Each settles facing the same way as it fades — upward, toward the keep above — and you understand they were never trapped down here, only kneeling in the dark to something far overhead.", "Something older than the garrison corners you in a dead-end cell, and your torch is not light enough to fight by. You break past it and flee back up the stair empty-handed, the dead behind you not pursuing but turning, as one, to face the slow corruption weeping down from the tower.")),
            opt("map",   "Map the safe route",    "DEX " + MEDIUM, check(Attribute.DEXTERITY, MEDIUM,
                         peace(1.5, 1.4, 20, "You chart a path around the worst of the dead and slip out with the lost cache under your arm. The garrison's ghosts never stir to stop you — they only kneel, every rusted helm bowed in the same direction, toward the slow corruption seeping down from the King's Tower far above."),
                         fight(1.4, 1.3, 20, "A wrong turn spills you straight into a knot of the restless dead, and you must hack a path back to the marked route. You win clear with the cache and your torch both, but the cold has soaked into the lost-and-found weight under your arm in a way no daylight will burn off.", "The maze of cells swallows your torch and then your nerve, and the dead close the gap your wrong turn opened. You stumble out by luck more than skill, hands empty, the whole sunken garrison behind you bowed in silent worship toward the spire you cannot see."))));

        put(KingdomQuestType.PATROL_RAMPARTS,
            "Something scaled the ramparts in the night.",
            opt("patrol", "Patrol and confront it", "", fight(1.8, 1.6, 30, "You walk the night wall until you catch the thing mid-climb and pry it loose to end it on the stones. It does not fight to escape so much as to keep climbing, clawing past you toward the inner tower even as it dies, hungry for the height.", "It uncoils out of a shadow you had already searched and routs you along the rampart before you can set your feet. You retreat down the stair half-blind, and behind you it resumes its climb — not over the wall and away, but up, toward the sickly light at the keep's crown.")),
            opt("track",  "Track the claw marks",   "DEX " + MEDIUM, check(Attribute.DEXTERITY, MEDIUM,
                          peace(1.6, 1.4, 25, "You trail the claw marks to a foul nest tucked under the battlements and put the thing down before it can shriek. It died facing the high tower, claws still reaching toward it — whatever climbed your walls had not come to raid, but to crawl closer to the thing that calls from the King's spire."),
                          fight(1.4, 1.3, 20, "The claw marks double back on themselves and the thing is suddenly behind you — but you turn inside its lunge and finish it against the merlons. It dies straining one last time toward the high spire, and you stand a long moment in the cold, unwilling to look up at what it wanted.", "You lose the trail in the dark, and that is when it finds you, striking from above with no warning at all. You barely break free and flee the rampart, leaving the nest unburned, and from the courtyard you can see the thing scaling onward — upward — toward the tower's call."))));

        put(KingdomQuestType.RAID_ENCAMPMENT,
            "An enemy camp sprawls below the walls, lightly watched.",
            opt("charge", "Charge the camp",         "", fight(1.9, 1.7, 35, "You hit the camp at a dead run with fire and steel and scatter the warband into the dark before they can form a line. The survivors do not run for the open country but back toward the keep and its tower, fleeing your blade into the very corruption they came down from.", "They form up faster than a roused camp has any right to, and the wall of them beats you back across the trampled ground. You withdraw bloodied with nothing to show, the enemy already turning their faces from the fight to the high tower, the way the devout turn at a bell.")),
            opt("sentry", "Slit the sentries first", "DEX " + HARD, check(Attribute.DEXTERITY, HARD,
                          fight(2.2, 1.9, 40, "One by one the sentries fold without a sound, and then you are loose in a sleeping camp, ending it tent by tent. The few who wake do not cry the alarm but kneel where they stand, eyes lifted past you to the tower, as if your blade were merely the form their devotion had been waiting to take.", "Your knife finds a throat half a breath too slow, the sentry's gurgle becomes a shout, and the whole camp boils up around you in arms. You cut your way back out and run, the chance lost, the warband already streaming inward toward the spire instead of after you."),
                          fight(1.5, 1.4, 25, "A blade misses its mark and the alarm goes up, but you abandon stealth for fury and carve through the waking camp before it can close. You leave it burning behind you, uneasy at how many of the dead fell with their faces turned up toward the keep's pale light.", "A botched cut wakes the watch, and you are surrounded and beaten down before you reach the first tent. You crawl off into the dark with empty hands and ringing ears, and the camp does not pursue — it has already forgotten you, kneeling toward the tower as one."))));

        put(KingdomQuestType.BREACH_THE_KEEP,
            "The inner keep is barred; the warlord's banner flies above.",
            opt("batter","Batter the gate down", "STR " + HARD, check(Attribute.STRENGTH, HARD,
                         peace(2.0, 1.8, 25, "The gate splinters under your shoulder and the warlord's defenders scatter rather than face you. They do not run for the walls or the woods — they flee inward and upward, deeper into the keep toward the tower's sickly light, choosing the corruption over the open gate you just made for them."),
                         fight(1.4, 1.3, 25, "The gate holds just long enough for the defenders to sally out around it — but you meet their charge head-on and break it, and the splintered gate is yours at last. They fall back inward and upward as they flee, choosing the tower's sick glow over the open road behind you.", "The gate holds, and the makeshift ram shatters under your last heave, the recoil throwing you flat among the wreckage. You are dragged clear by your own retreat, the warlord's banner still flying, the defenders within bowing toward a light that was never meant for living eyes."))),
            opt("court", "Fight through the courtyard", "", fight(1.7, 1.5, 35, "You carve a red path across the open courtyard and reach the keep's inner door with the warlord's men breaking before you. None of them flee out the gate at your back — they scramble deeper in, toward the tower, as if the corruption above were the only safety they still trust.", "The courtyard closes around you like a snare, the defenders pouring from every doorway until there is no forward and no back. You fight clear by inches and reel out the way you came with nothing won, the keep swallowing its men into the tower's glow behind you.")));

        put(KingdomQuestType.HUNT_WARLORD,
            "The warlord stands atop the keep, blade already drawn.",
            opt("duel", "Duel the warlord",          "", fight(1.6, 1.5, 40, "Steel rings on steel atop the keep until at last you slip his guard and the warlord falls at your feet. He dies with his ruined face turned up toward the tower above, mouthing something to it, and you do not stay to learn whether it answered.", "The warlord's blade finds you first and the rooftop tilts away beneath you into black. You wake slumped against the battlement, disarmed and aching, the warlord vanished into the keep, the tower's light pulsing overhead like a slow and patient heartbeat.")),
            opt("goad", "Goad him into a charge",    "LUCK " + HARD, check(Attribute.LUCK, HARD,
                        fight(2.2, 2.0, 45, "Your taunts find the raw nerve and he charges blind with rage, straight onto the blade you had waiting. As the fury drains from him his eyes drift upward to the spire, almost peaceful, as though he were only now going to meet the master he served.", "He reads the goad for what it is and makes you pay for the insult, his counter so brutal it scatters your footing and your plan. You break off the duel and stagger down the stair beaten, the warlord left standing under his banner, the tower's glow approving above him."),
                        fight(1.4, 1.3, 35, "He laughs off your taunts and comes on guard instead of charging, so you trade the trap for honest steel and grind him down the hard way. He topples at the last with his gaze climbing past you to the high spire, and the silence after feels less like victory than permission.", "Your goading only sharpens his fury, and a sharpened warlord is more than you can hold — he batters you to your knees and off the rooftop's edge. You catch yourself on the stair below and flee, the duel lost, his laughter chasing you down toward the courtyard and the tower's waiting light."))));

        // ── Crystal Grottoes — Prospecting ──────────────────────────────────────
        put(KingdomQuestType.GUARD_CRYSTAL_VEINS,
            "Thieves chip away at the glowing veins by lantern-light.",
            opt("drive", "Drive them off",        "", fight(1.8, 1.6, 30, "You fall on the thieves at their lanterns and scatter them coughing into the tunnels, the veins safe behind you. They do not curse you as they flee, only smile back over their shoulders, certain of something — as if the glowing stone had already promised them you would change your mind.", "They turn their picks and chisels on you in a frenzy, and the narrow tunnel gives you no room to answer it, so you fall back. As you go, the humming light of the veins seems to lean after you, patient and unbothered, like a voice that knows it has all the time it needs.")),
            opt("catch", "Catch them red-handed",  "DEX " + EASY, check(Attribute.DEXTERITY, EASY,
                         peace(1.5, 1.4, 20, "You corner the thieves over their loot and take back every glowing shard. They surrender without a struggle, smiling, and one of them whispers that the veins told them you would come — that the crystal speaks to anyone who listens long enough, and soon it will speak to you too."),
                         fight(1.4, 1.3, 20, "They hear you coming and turn to fight, but you break their little circle and pin them over the stolen shards. They yield grinning all the same, one murmuring that the veins had warned them of you — and that the crystal will get its word in eventually, with you as with them.", "They slip the loot away into the dark and slip your grasp with it, leaving you grasping at echoes and your own pride. The grotto hums softly as you withdraw, almost amused, and for a heartbeat you would swear the light shaped your name."))));

        put(KingdomQuestType.MAP_THE_GROTTO,
            "The grotto twists into a maze of mirrored crystal.",
            opt("chart", "Chart it carefully",         "DEX " + MEDIUM, check(Attribute.DEXTERITY, MEDIUM,
                         peace(1.6, 1.4, 25, "You hold your nerve through every mirrored turn and chart your way to an untouched vein. But the reflections never quite matched your movements — they answered them, a fraction early, as though something behind the glass were learning the map of you while you mapped its home."),
                         fight(1.4, 1.3, 20, "The mirrors fold you into a nest of crawlers before you see the turn, and you cut your way back out facet by shattering facet. You reach the untouched vein at last, unable to shake the sense that the reflections herded you into the fight to watch how you'd fare.", "You lose yourself among the answering reflections until you cannot tell your own shape from the dozen that mimic it, and the crawlers find you in the confusion. You stumble back out the way you think you came, empty-handed, the mirrored dark releasing you with what almost feels like curiosity."))),
            opt("push",  "Push through what blocks you", "", fight(1.8, 1.6, 30, "You put your shoulder and your blade to whatever the grotto throws across your path and smash through to the vein beyond. Every shard you break rings with a single sustained note, the same note, as if the whole maze were one voice and you had merely interrupted it mid-thought.", "The maze keeps changing its mind about where the walls are, and its denizens come at you from angles that should not exist, until they get the better of you. You retreat through corridors that rearrange behind you, certain now that the grotto was not blocking your way so much as deciding whether to let you through.")));

        put(KingdomQuestType.EXTRACT_GEODES,
            "Massive geodes line a ledge over a black drop.",
            opt("slow", "Work the ledge slowly", "", peace(0.9, 0.9, 8,  "Patient, careful work fills your pack with heavy geodes and you never once look down into the black drop. All the while a low chime hums up from the dark below the ledge — not the ring of struck crystal, but something steadier, a voice with no mouth, sounding out your name to see if it fits.")),
            opt("pry",  "Pry the biggest free",  "STR " + MEDIUM, check(Attribute.STRENGTH, MEDIUM,
                        peace(1.6, 1.4, 25, "You set your back to the great geode and wrench it free — a fortune in crystal cradled in your arms. The moment it parts from the ledge a soundless word presses into your skull, almost grateful, and you realize the thing you just took was never stone at all but a piece of something that wanted to be carried out."),
                        fight(1.4, 1.3, 20, "The ledge splinters under your strain and something stirs awake in the black drop below — but you haul yourself back onto solid stone and fight it off the rim until it sinks away. You keep your prize and your footing both, the soundless chime from the dark following you out like a question half-asked.", "The ledge gives way as the geode comes loose and you very nearly follow it down into the lightless drop. You catch the lip with torn fingers and drag yourself up with nothing, and as you flee the chime below shapes itself into your name, unhurried, sure you will come back to hear the rest."))));

        put(KingdomQuestType.SEAL_THE_FISSURE,
            "A fissure leaks a cold, humming light — and shapes move within.",
            opt("wall",  "Wall it off",            "", peace(0.9, 0.9, 8,  "You close the humming fissure behind a wall of stone and mortar and the cold light winks out. Just before the last brick goes in, the hum shapes itself into words only you can hear — calm, certain, promising that a wall means nothing to a thought, and that it will simply wait inside your head instead.")),
            opt("cull",  "Cull what crawls out",   "", fight(1.8, 1.6, 30, "You stand at the fissure's cold mouth and cut down everything that crawls into the humming light, until nothing more comes. The hum never falters through all of it, steady and unbothered by the slaughter, as though it were merely watching its hands be trimmed and would simply grow more.", "More pour out of the cold light than any blade can hold back, shape after shape pressing you off the ledge. You give ground and flee the humming dark, and the sound follows you up the tunnel, calm and even, certain it has only to wait you out.")),
            opt("seal",  "Read the resonance",     "LUCK " + HARD, check(Attribute.LUCK, HARD,
                         peace(2.0, 1.8, 30, "You match the seal to the fissure's exact pitch and the cold light folds shut without a tremor. To tune it you had to listen, truly listen, and the hum is in you now — a patient second voice beneath your thoughts, well pleased that you finally understand its song."),
                         fight(1.5, 1.4, 25, "You misjudge the pitch and the resonance lashes back, spilling the shapes out of the fissure all at once — but you carve a path clear and break for the tunnel mouth. The hum lets you go ringing in your skull, not angry, only noting where it ends and you begin.", "The hum slides under your thoughts and scrambles them before you can find its note, and you stumble away from the fissure with your mind full of static. You make it out, but a thin patient drone has lodged behind your eyes, and you suspect it is no longer entirely the grotto's."))));

        put(KingdomQuestType.CLEANSE_CRYSTAL_HORROR,
            "A horror of living crystal drags itself toward the surface.",
            opt("shatter","Shatter it",            "", fight(1.8, 1.6, 35, "You meet the crawling horror head-on and break it down blow by ringing blow into a drift of glittering shards. Even shattered the pieces keep humming the same low note, all of them in unison, and you back away before you can start to wonder whether it died at all or only scattered.", "Its facets throw your own blows back at you and its shards open you in a dozen places before you can close. You reel away leaving it half-broken and already knitting, the chorus of its hum rising behind you, patient and uninterrupted, as if it had never been in any danger at all.")),
            opt("core",   "Find its fractured core","DEX " + HARD, check(Attribute.DEXTERITY, HARD,
                          fight(2.2, 2.0, 45, "You read the fault lines to its true core, strike once, and the whole horror collapses inward and goes dark and silent. The sudden quiet is worse than the noise — a held breath in the rock, as though the rest of the grotto had felt the loss and was deciding what to make of you.", "The core you struck was a decoy grown to draw your blade, and the real mass engulfs you while you recover. You tear free and flee the closing crystal, and the hum it never broke off rides out with you, amused, having learned exactly how you hunt."),
                          fight(1.4, 1.3, 35, "You cannot find the flaw, so you break the horror the long and brutal way, hacking it down piece by stubborn piece. It falls at last, but the effort leaves the single note of it ringing in your teeth, and you are not certain the silence afterward is empty.", "It reforms faster than you can shatter it, every shard you knock loose flowing back into the mass, until you understand you are losing and break off. You flee the tireless thing up the tunnel, its hum never once faltering, certain now that you were never fighting a creature but a mind that merely wears one."))));

        put(KingdomQuestType.SLAY_CRYSTAL_BEAST,
            "The crystal beast wakes, its facets blazing.",
            opt("slay",  "Slay it",                 "", fight(1.6, 1.5, 40, "You wade through its blazing facets and bring the crystal beast down piece by glittering piece until its light goes out. Where it lies broken the shards still chime faintly to one another, passing something along in the dark, and you do not linger to hear what they decide.", "Its blaze sears the sight from you and its facet-edged claws do the rest, and the grotto tilts away into a ringing white. You come to slumped against the cold wall, blind and bleeding and beaten, the beast gone, its low hum threaded now through the ache behind your eyes.")),
            opt("blind", "Blind it with its light", "LUCK " + EPIC, check(Attribute.LUCK, EPIC,
                         fight(2.3, 2.1, 45, "You angle a loose shard to catch its own glare and throw the blaze back into its facets, and while it reels dazzled you strike it down. In the silence after, its scattered light still gutters with a faint rhythm, like a thought trying to finish itself, and you leave before it can.", "The light scatters wrong off your shard and sears your own eyes instead, and the beast is on you before you can blink it clear. You flee half-blind through corridors you cannot see, its triumphant hum lighting the way it wants you to go, deeper, not out."),
                         fight(1.4, 1.3, 35, "The clever trick fails outright, so you throw it aside and face the blazing beast on its own terms, outlasting its fury blow by blow. It falls dark at last, and you stand panting in the sudden gloom, the silence humming faintly at the edges where the light used to be.", "Dazzled by your own gambit, you lose the beast in the glare and it batters you down before your sight clears. You crawl away from its blaze with nothing won, a sliver of its cold light seeming to ride out behind your eyes, patient, already at home there."))));

        // ── Blessed Sea — sacred waters ─────────────────────────────────────────
        put(KingdomQuestType.CLEANSE_THE_TIDES,
            "A foulness taints the sacred shallows.",
            opt("rite",  "Perform the rite",        "LUCK " + EASY, check(Attribute.LUCK, EASY,
                         peace(1.5, 1.4, 20, "Your rite draws the taint out of the shallows and the sacred water runs bright and clear again. Where it laps at your ankles every cut and ache you carried closes over and stops hurting — and the clear water does not let go of your feet, lingering warm against your skin as if it would rather you stayed in it forever."),
                         fight(1.4, 1.3, 20, "The rite falters mid-word and the foulness gathers itself into a shape that lunges — but you cut it apart in the shallows before it can fully form. The cleansed water closes warm around your wounds as you stand panting, and you have to wade out quickly, before it can finish mending you into staying.", "The taint twines around your legs and drags you under before the rite can take, and the sacred water fills your mouth like a welcome. You break the surface coughing on the sand, spared but not freed — the gentle shallows release you slowly, reluctantly, the way one gives up something it meant to keep."))),
            opt("drive", "Drive out the befouler",  "", fight(1.8, 1.6, 30, "You wade in and drive the foul thing thrashing out of the sacred shallows until the water runs clean behind it. The healed shallows lap at your shins all the while, warm and clinging, closing your cuts as fast as the fight opens them, in no hurry to let you back onto dry land.", "The befouler twists past your guard and pulls you down into the murk, and the blessed water folds over your head almost lovingly. You drag yourself ashore half-drowned and empty-handed, the tide reaching after your heels in slow warm fingers, sorry to see you go.")));

        put(KingdomQuestType.BLESS_THE_SHALLOWS,
            "Pilgrims wait for the waters to be blessed, but something lurks offshore.",
            opt("bless", "Bless the waters in peace", "", peace(0.9, 0.9, 8,  "The blessing settles over the shallows and the pilgrims wade in weeping with joy, their sores and limps washing away. None of them want to come back to shore, and when you call them in they only smile and drift a little deeper, as the gentle water folds around them like an embrace that has finally found what it was holding out for.")),
            opt("clear", "Clear the lurker first",    "", fight(1.8, 1.6, 30, "You wade out past the pilgrims and drive the lurker off into deep water, then come back to bless the calm you bought. The shallows go bright and warm around the kneeling faithful as the rite takes, and none of them rise to follow you out — they only wade deeper, smiling, into water that closes around them like an answered prayer.", "The lurker takes you before you can finish the rite, hauling you down into the dark where the pilgrims cannot reach. You fight back to the surface and drag yourself ashore spent, the blessing unspoken, and the pilgrims watch from the water with the patient, dreaming eyes of people who have already decided not to come back.")),
            opt("calm",  "Calm them, read the tide",  "LUCK " + MEDIUM, check(Attribute.LUCK, MEDIUM,
                         peace(1.6, 1.4, 25, "You read the water and time the rite to a kind, rising tide; the pilgrims bless your name as the healing takes. But the tide came in too willingly, swelling to meet your words like a thing eager to be invited closer — and now it sits higher up the sand than it has any right to, in no hurry to withdraw."),
                         fight(1.4, 1.3, 20, "You misread the tide and it turns foul beneath your feet, the lurker rising with it — but you put yourself between it and the pilgrims and beat it back into the swell. The water you saved them from laps warm and grateful at your legs, healing every blow it lands, oddly loath to let the fight, or you, end.", "The tide sours, panic scatters the pilgrims, and the lurker strikes through the chaos to drag you under the blessed water. You crawl out alone and beaten, the rite ruined, and the shallows ease back from the sand with a slow reluctance, as if it had counted on adding you to its quiet, smiling congregation."))));

        put(KingdomQuestType.ESCORT_PILGRIMS,
            "Pilgrims must cross the drowned causeway by dusk.",
            opt("guide", "Guide them across",        "DEX " + MEDIUM, check(Attribute.DEXTERITY, MEDIUM,
                         peace(1.6, 1.4, 25, "You read the safe stones one by one and bring every pilgrim across the drowned causeway dry-shod. The sea held itself low and still the whole crossing, parting like a host that wished you well — and only after the last pilgrim stepped ashore did the water rush back over the path, fast and hungry, as if it had been counting heads and come up one short."),
                         fight(1.4, 1.3, 20, "A pilgrim slips from the stones and the deep stirs at the taste of it — but you haul the strayer back and stand off whatever rose to meet the splash until the crossing is made. The water settles only once every pilgrim is ashore, drawing back slow and grudging, as though robbed of a tithe it had thought already owed.", "The causeway floods between one step and the next, scattering your charges into the surf as cold shapes rise around them. You drag the nearest to dry land and lose the rest to the dark, and the sea closes smooth and satisfied over the path, having taken its count and let you, this once, off the tally."))),
            opt("guard", "Guard the rear from the deep","", fight(1.8, 1.6, 30, "You set yourself at the rear of the column and hold off the dripping things that climb from the drowned road until the last pilgrim steps ashore. The deep gives up the fight reluctantly, sinking back without a splash, the way a host clears the table of a guest who would not stay.", "Something rises out of the drowned causeway and takes the stragglers before you can reach them, then nearly takes you too. You wrench free of the cold grip and stagger to dry land alone, the lost pilgrims gone under without a cry, the sea already smooth again and counting what is left.")));

        put(KingdomQuestType.PURIFY_THE_REEF,
            "The reef's glow has dimmed to a sickly grey.",
            opt("channel","Channel the blessing",   "LUCK " + MEDIUM, check(Attribute.LUCK, MEDIUM,
                         peace(1.6, 1.4, 25, "You pour the blessing into the dying coral and light spreads back through the reef in a slow, golden bloom. The renewed glow reaches out past the reef to gild your own veins beneath the skin, warm and welcome and wrong — for the same blessing that heals the reef is what is leaking into the world, and now a little of it is leaking into you."),
                         fight(1.4, 1.3, 20, "The blessing curdles in your hands and something hauls itself up out of the grey rot, but you put it down before it can find its feet and finish the healing over its ruin. The light blooms back through the reef and into your own skin as it does, warm and wrong, mending you whether you asked it to or not.", "The grey rot surges up to meet the curdled blessing and takes hold of you with it, and for a moment the sickly light and your own pulse beat as one. You tear loose and flee the dimming reef empty-handed, a faint cold glow lodged under your skin now, leaking in where the world's wound and yours have started to blur."))),
            opt("burn",  "Burn out the rot",         "", fight(1.8, 1.6, 30, "You follow the grey blight to its writhing heart and cut it out at the source until clean water runs through the reef again. The renewed glow spreads quick and eager up your arms as you work, healing the burns it costs you, and you have to leave fast — before the cure decides you are part of the reef worth keeping.", "The rot fights back, spreading over your hands and up your arms faster than you can carve it away, until you must abandon the reef to save yourself. You wade out shaking, the blight withdrawing behind you almost politely, certain the leak that feeds it has all the time it needs to reach you again.")));

        put(KingdomQuestType.BANISH_THE_DROWNED,
            "The drowned rise from the sacred deep, dripping and silent.",
            opt("banish","Banish them with the rite","LUCK " + HARD, check(Attribute.LUCK, HARD,
                         peace(2.0, 1.8, 30, "Your rite unmakes the silent dead and one by one they sink back beneath the blessed water to rest. As each goes under it turns its dripping face to you, not in hatred but in welcome — for the deep does not lose them, only keeps them, and the rite that sent them down was the same holy water that called them up to begin with."),
                         fight(1.5, 1.4, 25, "The rite breaks apart on your tongue and the silent drowned close the ring around you — but you carve a gap with steel and salt and stand your ground until they sink away. They go under unhurried, dripping faces still turned to you in something like welcome, in no doubt the sacred water will simply call them up again.", "The rite shatters and cold dead hands fasten on you and haul you toward the deep, the blessed water rising eager to your chin. You wrench free at the brink and crawl ashore choking, the drowned slipping back beneath the surface unbothered, patient as the holy tide that keeps raising them."))),
            opt("force", "Put them down by force",   "", fight(1.8, 1.6, 30, "You wade into the silent ranks of the drowned and scatter them with steel and blessed salt until the sacred water lies still again. They sink without protest, faces tilting up to you as they go, for force only sends them back to the deep that holds them — and the same holy water will hand them up once more.", "They rise faster than you can put them down, and for every dripping shape you scatter two more climb from the blessed deep, until the numbers drive you back. You retreat up the strand spent and salt-blind, the drowned settling beneath the calm water to wait, certain, as the patient deep is certain, of the next time.")));

        put(KingdomQuestType.GUARD_SACRED_REEF,
            "A leviathan of the deep coils around the sacred reef.",
            opt("defend","Defend the reef",          "", fight(1.6, 1.5, 40, "You stand on the sacred reef and meet the leviathan coil by coil until it gives up its hold and slides back down into the abyss. The blessed water around you knits your wounds even as it sustains the thing you fought, and you climb out fast, before the reef's gift can decide you belong to the deep as well.", "The leviathan's coils close around the reef and you with it, and the holy shallows run red before you tear yourself loose. You wash up on the rocks broken and gasping, the beast withdrawn but not gone, the sacred deep that birthed it lapping warm at your wounds as if it would rather you stayed.")),
            opt("sing",  "Sing the old verse to lull it","LUCK " + EPIC, check(Attribute.LUCK, EPIC,
                         fight(2.3, 2.1, 45, "The old verse settles over the leviathan and its coils go slack as it sinks into something like sleep — and you drive your blade home while it dreams. It dies slow and unresisting, sliding back into the blessed deep that made it, and the warm water laps after you up the rocks, unwilling to let its singer leave.", "The verse cracks on a wrong note and wakes the leviathan to full wrath, its coils lashing the reef to foam around you. You dive clear and flee through bloodied water, the beast bellowing behind you, the sacred deep heaving it on like a sea defending its own."),
                         fight(1.4, 1.3, 35, "Your voice falters and the verse fails to bind it, so you face the roused leviathan with steel instead and outlast its slow, vast fury. It sinks at last into the abyss that bore it, and the blessed water clings warm to your skin as you haul out, loath to give you back to the air.", "Your song falters and the deep itself seems to drown it, the leviathan surging up through the broken verse to nearly take you with it. You are dragged under and spat back out by a swell you cannot account for, washing onto the reef alive, the sacred sea sparing its singer for a song still unfinished."))));
    }
}
